### ISSUE TITLE
Allow argument for package list

### ISSUE THREAD

**Issue by friendly** [luisDVA/hexsession#2] opened 2024-10-09 00:12 UTC
Nice idea!

Getting the list of packages from those attached may be easy, but it creates problems for package dependencies that I **don't want to include** in the hexsession display.

Can you add a `packages` argument so that I could say simply

```
pkgs <- c("heplots", "candisc", "mvinfluence", "genridge", "VisCollin",
          "matlib", "gellipsoid", "twoway",
          "vcdExtra", "nestedLogit",  
          "HistData", "Guerry", "Lahman" )
hexsession::make_tile(pkgs)
```

As it is, with this list, `make_tile()` includes packages which my packages Depend on:
broom, car, carData, ...
that I don't want in the display

**Comment by friendly** [comment] 2024-10-09 02:04
FYI: Here's what I get from the code above.
I don't want any of those rendered a black hexs, except for `twoway` and `candisc`. I haave logos for those, and have to investigate why they aren't found

![image](https://github.com/user-attachments/assets/756ab2d1-3c2a-4b64-a2a6-a183b12861fd)

**Comment by luisDVA** [comment] 2024-10-09 16:43
thanks for the feedback!
passing a vector of package names rather than those attached to the search path seems like a good option. They would need to be installed though, so that the logos can be retrieved. I'll look into this next time I work on the package!

**Comment by fontikar** [comment] 2024-10-25 05:27
Hi @luisDVA this is a super cool package idea!!! 🤩 

I had a quick play with it today. 
I thought it would be cool to create an interactive hex sticker tile for my [Quarto website](https://github.com/fontikar?tab=repositories) which is also using `renv`

Like @friendly, packages under "Depends" in the DESCRIPTION file for a nominated package does come up in the tile which may be a unwanted effect of {hexsession}

1/4 of my R packages are not on CRAN, but all have hex stickers in either the `inst/figures` or `man/figures` folders (if they have a pkgdown website). I was surprised to see that `make_tile()` did not find the hex stickers! 

Code to reproduce:

```
# renv::install("APCalign")
# remotes::install_github("traitecoevo/austraits")
# remotes::install_github("traitecoevo/infinitylists")
# remotes::install_github("fontikar/ohwhaley")

library(austraits)
library(APCalign)
library(infinitylists)
library(ohwhaley)

hexsession::make_tile()
```

<img width="1237" alt="Screenshot 2024-10-25 at 4 20 49 PM" src="https://github.com/user-attachments/assets/961736b4-6fa0-4f60-9691-425546ea4294">

**Comment by luisDVA** [comment] 2024-10-25 06:02
Hi @fontikar ,
Just had a very quick look using `ohwhaley` (very cute sticker btw), austraits, and `infinitylists`

There are indeed logos bundled with the packages, but they don't show up because of my overly simple heuristic of only considering png or svg files that have 'logo' in their filename (and svgs don't work yet :sweat_smile: ). austraits does have 'logo' in the filename that's why it works in your example.

Because packages can come with lots and lots of images I couldn't think of any other approach, and people following the tidy style guide generally just name the images with their logo as "logo".

Do you have any ideas?
Thanks for the feedback and for the galah sticker you gave me, its already on my laptop :)

**Comment by luisDVA** [comment] 2024-10-29 07:19
Hi @fontikar 
I thought about your issue and came up with the following approach: 

![userprmpt](https://github.com/user-attachments/assets/ebc097c6-711a-4799-ac21-ca0cad5523f6)

after selecting the logos interactively, the output looks like this:

![conversions](https://github.com/user-attachments/assets/81dbdcf9-5236-4771-9b31-ac3deb7e8e73)

Try it out!
Additionally, svg logos now work too

**Comment by fontikar** [comment] 2024-10-29 21:16
Hey @luisDVA oh my goodness I'm sorry I hadn't replied yet, but when I saw your last comment I was thinking of enlisting `menu()` as well so well done on implementing it! I'll take it for a spin soon! 

How do you think packages under "Depends" should be handled?

**Comment by luisDVA** [comment] 2024-10-29 21:35
Thanks @fontikar. I'm slowly realizing that working with packages attached to the search path may not be ideal. A straightforward solution for excluding logos for packages not explicitly loaded with `library` may be to add an argument to `make_tile` for excluding particular packages. What do you think?

by the way I made more improvements to the little `menu` prompt since my last comment here

**Comment by luisDVA** [comment] 2024-10-29 21:39
also, @friendly these latest commits might be relevant to your original issue

**Comment by friendly** [comment] 2024-10-29 22:23
To go back to my original querry and suggestion: 

* `make_tile()` should have a `packages =` argument. If specified, it can assume that all pkgs listed are installed (or signal an error).
* then there is no need to worry about any `Depends:`

All of this discussion stems from, I think, a poor initial design choice, that `hexsession` **must** find the packages from those currently loaded.

thanks for listening ...

**Comment by luisDVA** [comment] 2024-10-30 23:36
hi! 
this [commit](https://github.com/luisDVA/hexsession/commit/c58c58d51d3a527352f6c47a4b41d65868f44b5e) adds a `packages` argument to `make_tile`, as suggested by @friendly. The default NULL will make the tile for the packages attached to the search path but custom vectors of library names now work as long as the packages are installed. 
thanks for the feedback!
Closing

**Comment by friendly** [comment] 2024-10-31 00:50
Please reopen this issue to consider how `snap_tile()` should work with a `packages` argument to `make_title()`

With your latest commit (thanks!) I get an error:

```
remotes::install_github("luisdva/hexsession")
library(hexsession)

pkgs <- c("heplots", "candisc", "mvinfluence", "genridge", "VisCollin",
          "matlib", "gellipsoid", "twoway",
          "vcdExtra", "nestedLogit",  
          "HistData", "Guerry", "Lahman"
          )

hexsession::make_tile(packages = pkgs)

snap_tile("hexsession.png")
```

The error is:

```
> snap_tile("hexsession.png")
Error in snap_tile("hexsession.png") : 
  No file to capture. Did you create your tile of logos?
```

**Comment by luisDVA** [comment] 2024-10-31 16:14
reopening and will investigate!

**Comment by luisDVA** [comment] 2024-11-08 21:23
hi @friendly 

with the code below and the current dev version I produced this tile:

![hexsessiontest](https://github.com/user-attachments/assets/695a55ac-c959-467b-9912-1fe2ca863e70)


When you run make_tile are you getting an html file produced in the new folder in your working directory?

```

remotes::install_github("luisdva/hexsession")

pkgs <- c("heplots", "candisc", "mvinfluence", "genridge", "VisCollin",
          "matlib", "gellipsoid", "twoway",
          "vcdExtra", "nestedLogit",  
          "HistData", "Guerry", "Lahman"
)

pak::pkg_install(pkgs)

hexsession::make_tile(packages = pkgs)
hexsession::snap_tile("hexsessiontest.png")
```

**Comment by luisDVA** [comment] 2024-12-02 21:00
Hi @friendly !
all working nicely after installing dev versions:
![hexsessiontestDec](https://github.com/user-attachments/assets/06b213df-8169-4962-b19a-2769dd516277)

all those logos look quite nice together.  I'm not sure how the tile can be embedded in a quarto website yet. Just figured it out recently for jekyll though.

**Comment by friendly** [comment] 2024-12-02 21:37
Thanks so much for pursuing this. You've made hexsession more generally useful.
At the moment, I'm happy just to do this as a static image.

**Closed as completed** 2024-12-02 21:51 UTC
